service: serverless

provider:
  name: aws
  runtime: nodejs8.10
  profile: monstercode
  region: us-west-1
  stage: dev

plugins:
  - serverless-offline

functions:  
  api:
    handler: src/api/api.handler
    events:
      - http: GET /api

  todos:
    handler: src/api/todos.handler
    events:
      - http: GET /todos
    
  todo:
    handler: src/api/todo.handler
    events:
      - http: GET /todos/{id}
    
