org: gilberts
app: todo-serverless
service: serverless

provider:
  name: aws
  runtime: nodejs8.10
  # profile: todo-serverless-profile
  # region: us-west-1
  # stage: dev

plugins:
  - serverless-offline

functions:  
  api:
    handler: src/api/api.handler
    events:
      - http: ANY /
      - http: 'ANY /{param+}'

  # todos:
  #   handler: src/api/todos.handler
  #   events:
  #     - http: GET /todos
    
  # todo:
  #   handler: src/api/todo.handler
  #   events:
  #     - http: GET /todos/{id}
    
